production:
  brcm:
    uri: 'http://services:80/v2/accounts'
    auth_scheme: 'Wesabe'
  grendel:
    uri: 'http://services:81'

development:
  brcm:
    uri: 'http://localhost:8080/v2/accounts'
    auth_scheme: 'Wesabe'
  grendel:
    uri: 'http://localhost:8081'
  redis:
    uri: 'redis://localhost:6379'
    start_command: 'redis-server config/redis.conf'
    pid_file: '/var/run/redis.pid'
    log_file: '/var/log/redis.log'

test:
  brcm:
    uri: 'http://services.test:8080/v2/accounts'
    auth_scheme: 'Wesabe'
  grendel:
    uri: 'http://services.test:8081'
